version: '3.4'

services:
  catalogDb:
    image: postgres
    container_name: catalogDb
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: CatalogDb
    ports:
      - "5434:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/
  
  basketDb:
    image: postgres
    container_name: basketDb
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: BasketDb
    ports:
      - "5433:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data/
    
  orderDb:
    image: mcr.microsoft.com/mssql/server
    container_name: orderDb
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Serhiy0808
    ports:
      - "1433:1433"
  
  messageBroker:
    image: rabbitmq:management
    container_name: messageBroker
    hostname: ecommerce-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    
  distributedCache:
    image: redis
    container_name: distributeCache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    
  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: Catalog.Api/Dockerfile
    ports:
      - "6000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ConnectionStrings__DefaultConnection: Server = catalogDb;Port = 5432;Database = CatalogDb;User Id=postgres;Password=postgres;Include Error Detail=true
    depends_on:
      - catalogDb
        
  basket.api:
    image: basket.api
    build:
      context: .
      dockerfile: Basket.Api/Dockerfile
    ports:
      - "6001:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ConnectionStrings__DefaultConnection: Server = basketDb;Port = 5432;Database = BasketDb;User Id=postgres;Password=postgres;Include Error Detail=true
      ConnectionStrings__Redis: distributedCache:6379
      GrpcSettings__DiscountUrl: http://discount.grpc:8080
      MessageBroker__Host: amqp://ecommerce-mq:5672
      MessageBroker__UserName: guest
      MessageBroker__Password: guest
    depends_on:
      - basketDb
      - distributedCache
      - discount.grpc
      - messageBroker
  
  ordering.api:
    image: ordering.api
    build:
      context: .
      dockerfile: Ordering.Api/Dockerfile
    ports:
      - "6003:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ConnectionStrings__DefaultConnection: Server = orderDb;Database = OrderDb;User Id=sa;Password=Serhiy0808;Encrypt=True;TrustServerCertificate=true
      MessageBroker__Host: amqp://ecommerce-mq:5672
      MessageBroker__UserName: guest
      MessageBroker__Password: guest
    depends_on:
      - orderDb
      - messageBroker

  discount.grpc:
    image: discount.grpc
    build:
      context: .
      dockerfile: Discount.Grpc/Dockerfile
    ports:
      - "6002:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ConnectionStrings__Database: Data Source = discountDb
      
volumes:
  postgres_catalog:
  postgres_basket:
  redis_data:

  
