version: '3.4'

services:
  catalogDb:
    image: postgres
    container_name: catalogDb
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: CatalogDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/

volumes:
  postgres_catalog:
