version: '3.4'

services:
  catalogDb:
    image: postgres
    container_name: catalogDb
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: CatalogDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/
  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: Catalog.Api/Dockerfile
    ports:
      - "6000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ConnectionStrings__DefaultConnection: Server = catalogDb;Port = 5432;Database = CatalogDb;User Id=postgres;Password=postgres;Include Error Detail=true
    depends_on:
      - catalogDb
    
volumes:
  postgres_catalog:
